name: Release Poke App on Render

on:
  push:
    branches:
      - main

jobs:
  publish-app:
    name: Publish App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
